# Welcome to Jekyll!
# in the templates via {{ site.myvariable }}.
title: RateMyReptiles
author: Lord Sauron
email: lord@sauron.mordor
# nachiket@ratemydonkeys.com
description: >- # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.ratemyreptiles.com" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

permalink: /:year/:month/:day/:title/

future: true

minima:
  show_excerpts: true


# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
